name: Opam Dependency Submission

on:
  workflow_dispatch:

concurrency:
  group: opam-dependency-submission
  cancel-in-progress: true

permissions: read-all

jobs:
  opam-dependency-submission:
    name: Opam Dependency Submission

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1.1"
          opam-depext: false
          dune-cache: true

      - name: Opam Dependency Submission
        uses: ocaml/setup-ocaml/analysis@v2
